# Mocha options
# https://mochajs.org/#configuring-mocha-nodejs
# https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml

app: shipengine
watch-files: ["src/**/*", "test/**/*.js"]
spec:
  # Test fixtures
  # - test/fixtures/**/*.js

  # Test specs
  - test/specs/**/*.spec.js

recursive: true
require: source-map-support/register
