# Mocha options
# https://mochajs.org/#configuring-mocha-nodejs
# https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml

app: shipengine
watch-files: ["src/**/*", "test/**/*.js"]
timeout: 10000
spec:
  # Test fixtures
  # Test specs
  - test/specs/**/*.spec.js

recursive: true
require:
  - source-map-support/register
  - test/support/mocha-hooks
