name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      # can be replaced with $default-branch macro.
      - main
      - develop
jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Lint & Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest # buggy
          - windows-latest
        node:
          - 12.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Hoverfly for Windows
        if: ${{ matrix.os == 'windows-latest'}}
        uses: engineerd/configurator@v0.0.5
        with:
          name: hfly.exe
          fromGitHubReleases: true
          urlTemplate: https://github.com/SpectoLabs/hoverfly/releases/download/{{version}}/hoverfly_bundle_windows_amd64.zip
          repo: SpectoLabs/hoverfly
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
          pathInArchive: "hoverfly.exe"

      - name: Start Hoverfly for Windows
        if: ${{ matrix.os == 'windows-latest'}}
        run: |
          Start-Process -FilePath hfly -Args "-webserver -tls-verification=false -response-body-files-path simengine"

      - name: Start Hoverfly for Linux
        if: ${{ matrix.os == 'ubuntu-latest'}}
        run: docker-compose -f simengine/docker-compose.yaml up -d

      - name: Start Hoverfly for MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install SpectoLabs/tap/hoverfly && hoverfly -webserver -response-body-files-path simengine > /dev/null &

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci

      - run: npm run test

  deploy:
    name: Deploy to NPM
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - tests
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true
          tag: alpha

  publish-docs:
    name: Publish Documentation
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

      - name: Install Literate
        uses: engineerd/configurator@v0.0.5
        with:
          name: lit
          url: https://zyedidia.github.io/literate/binaries/literate-linux64.tar.gz
          pathInArchive: lit

      - name: Generate Docs
        run: npm run compile

      - name: Commit Generated Docs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f docs
          git commit -m "generate docs [skip ci]" || echo "nothing to commit."

      - name: Push Docs to Branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Publish to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
